import AppKit
import CryptoKit
import Foundation

/// There is no clipboard-change notification on macOS. None. Polling
/// `changeCount` is the only approach (PRD HP-1), and it's what every clipboard
/// manager does.
final class PasteboardMonitor {
  static let shared = PasteboardMonitor()

  /// Apps that mark their pasteboard contents as not-for-history.
  /// 1Password, Bitwarden, and Apple Passwords set `ConcealedType`.
  private static let skipTypes: Set<NSPasteboard.PasteboardType> = [
    .init("org.nspasteboard.ConcealedType"),
    .init("org.nspasteboard.TransientType"),
    .init("org.nspasteboard.AutoGeneratedType"),
  ]

  /// A single copy of a 50 MB log file would blow both the 5 MB database budget
  /// and the 60 MB memory budget (DECISIONS S-4).
  private static let maxContentBytes = 1_000_000

  /// Password managers `declareTypes` and then `setData`. A poll landing between
  /// the two reads the string before `ConcealedType` is declared and stores the
  /// password silently. Waiting for the change count to hold still closes that
  /// window (DECISIONS S-2).
  private static let settleDelay: Duration = .milliseconds(80)

  private let pasteboard = NSPasteboard.general
  private var timer: Timer?
  private var lastChangeCount: Int

  /// Set by our own writes to the pasteboard. Without it, every paste bumps
  /// `changeCount`, gets re-captured, and reshuffles the history
  /// (DECISIONS S-1). Phase 4 will call `ignoreNextChange()` from the paster.
  private var ignoredChangeCount: Int?

  var isPaused = false

  private init() {
    lastChangeCount = pasteboard.changeCount
  }

  func start() {
    guard timer == nil else { return }
    let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
      self?.tick()
    }
    // Lets the OS coalesce our wakeups with others instead of demanding a
    // precise 500 ms, which is what keeps idle CPU under the NFR budget.
    timer.tolerance = 0.2
    RunLoop.main.add(timer, forMode: .common)
    self.timer = timer
  }

  func stop() {
    timer?.invalidate()
    timer = nil
  }

  /// Call immediately after writing to the pasteboard ourselves.
  func ignoreNextChange() {
    ignoredChangeCount = pasteboard.changeCount + 1
  }

  private func tick() {
    let current = pasteboard.changeCount
    guard current != lastChangeCount else { return }
    lastChangeCount = current

    guard !isPaused else { return }

    if ignoredChangeCount == current {
      ignoredChangeCount = nil
      return
    }

    Task { @MainActor in
      try? await Task.sleep(for: Self.settleDelay)
      // Another copy landed while we waited; the next tick will handle it.
      guard self.pasteboard.changeCount == current else { return }
      self.capture()
    }
  }

  @MainActor
  private func capture() {
    let types = Set(pasteboard.types ?? [])
    guard types.isDisjoint(with: Self.skipTypes) else { return }

    guard let content = pasteboard.string(forType: .string),
          !content.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
          content.utf8.count <= Self.maxContentBytes
    else { return }

    let app = NSWorkspace.shared.frontmostApplication

    ItemRepository.save(
      Item(
        content: content,
        preview: Self.preview(of: content),
        sourceBundleID: app?.bundleIdentifier,
        sourceAppName: app?.localizedName,
        copiedAt: Int64(Date().timeIntervalSince1970 * 1000),
        contentHash: Self.hash(content)
      )
    )
  }

  /// Collapses whitespace so multi-line stack traces stay readable in one row.
  static func preview(of content: String) -> String {
    let collapsed = content
      .trimmingCharacters(in: .whitespacesAndNewlines)
      .split(whereSeparator: \.isWhitespace)
      .joined(separator: " ")
    return String(collapsed.prefix(200))
  }

  static func hash(_ content: String) -> String {
    SHA256.hash(data: Data(content.utf8))
      .compactMap { String(format: "%02x", $0) }
      .joined()
  }
}
