import AppKit
import CryptoKit
import Foundation

/// There is no clipboard-change notification on macOS. None. Polling
/// `changeCount` is the only approach (PRD HP-1), and it's what every clipboard
/// manager does.
final class PasteboardMonitor {
  static let shared = PasteboardMonitor()

  /// Apps that mark their pasteboard contents as not-for-history.
  /// 1Password, Bitwarden, and Apple Passwords set `ConcealedType`.
  private static let skipTypes: Set<NSPasteboard.PasteboardType> = [
    .init("org.nspasteboard.ConcealedType"),
    .init("org.nspasteboard.TransientType"),
    .init("org.nspasteboard.AutoGeneratedType"),
  ]

  /// A single copy of a 50 MB log file would blow both the 5 MB database budget
  /// and the 60 MB memory budget (DECISIONS S-4).
  private static let maxContentBytes = 1_000_000

  /// RTF gets the same 1 MB cap as the plain string, not a larger one. It goes
  /// into the same SQLite row, so it spends the same 5 MB database budget
  /// (FR-2.5), and rich text inflates unpredictably — styling, fonts and
  /// hex-encoded embedded images can make an RTF many times the size of its
  /// plain text. Over the cap the RTF is dropped and the plain string is still
  /// stored: the item stays captured and searchable, and the only loss is
  /// formatting on paste, which is exactly what the app did before FR-1.2.
  private static let maxRTFBytes = 1_000_000

  /// Images get their own, more generous cap: they go to disk rather than into
  /// SQLite (FR-2.2), so the 1 MB text limit — which exists to protect the 5 MB
  /// database budget — does not apply. A full-screen PNG on a 6K Retina display
  /// runs 5–15 MB, so anything under that would reject ordinary screenshots.
  /// 32 MB still bounds the transient decode against the memory budget.
  private static let maxImageBytes = 32_000_000

  /// Password managers `declareTypes` and then `setData`. A poll landing between
  /// the two reads the string before `ConcealedType` is declared and stores the
  /// password silently. Waiting for the change count to hold still closes that
  /// window (DECISIONS S-2).
  private static let settleDelay: Duration = .milliseconds(80)

  private let pasteboard = NSPasteboard.general
  private var timer: Timer?
  private var lastChangeCount: Int

  /// Why the timer is currently down, one entry per system reason
  /// (DECISIONS S-19). A set rather than a bool because the reasons overlap and
  /// do not nest: closing the lid posts display sleep *and* system sleep, and a
  /// machine woken by the power button is awake while still locked — so the last
  /// resume to arrive has to be the one that restarts polling, not the first.
  ///
  /// Deliberately separate from `isPaused`: a user who chose to pause and a
  /// system that went to sleep are different states, and waking must not
  /// silently un-pause the user.
  private var suspendedBy: Set<String> = []

  /// Set by our own writes to the pasteboard. Without it, every paste bumps
  /// `changeCount`, gets re-captured, and reshuffles the history
  /// (DECISIONS S-1). Phase 4 will call `ignoreNextChange()` from the paster.
  private var ignoredChangeCount: Int?

  /// FR-7.4. Deliberately not a member of `suspendedBy`: a user who paused and a
  /// machine that went to sleep are different states, and waking must not
  /// un-pause anyone (DECISIONS D-16).
  ///
  /// Read through rather than mirrored into a stored property, so there is one
  /// copy of the answer and no way for the timer and the checkbox to disagree.
  /// Costs a cached CFPreferences lookup twice a second.
  var isPaused: Bool { Preferences.isPaused }

  /// FR-7.3. Not persisted and not a counter — "the next copy" means the next
  /// one, so quitting with it armed disarms it rather than surprising the user
  /// on a later launch.
  private(set) var ignoresNextCapture = false

  private init() {
    lastChangeCount = pasteboard.changeCount
    observeSleepAndLock()
  }

  /// Nothing can reach the pasteboard while the display is off, the machine is
  /// asleep, or the screen is locked, so 2 Hz of wakeups buys nothing and is
  /// exactly what shows up in battery diagnostics with the lid shut
  /// (DECISIONS S-19, FR-7.6's neighbourhood).
  ///
  /// Three separate sources because they are three separate events: the lid can
  /// close without the machine sleeping, the machine can sleep without the
  /// screen locking, and screen lock is the only one of the three with no public
  /// notification — `com.apple.screenIsLocked` is undocumented but stable, and
  /// is what this class of app uses.
  private func observeSleepAndLock() {
    let workspace = NSWorkspace.shared.notificationCenter
    for (name, reason) in [
      (NSWorkspace.screensDidSleepNotification, "display"),
      (NSWorkspace.willSleepNotification, "system"),
    ] {
      workspace.addObserver(forName: name, object: nil, queue: .main) { [weak self] _ in
        self?.suspend(reason)
      }
    }
    for (name, reason) in [
      (NSWorkspace.screensDidWakeNotification, "display"),
      (NSWorkspace.didWakeNotification, "system"),
    ] {
      workspace.addObserver(forName: name, object: nil, queue: .main) { [weak self] _ in
        self?.resume(reason)
      }
    }

    let distributed = DistributedNotificationCenter.default()
    distributed.addObserver(forName: .init("com.apple.screenIsLocked"), object: nil, queue: .main) {
      [weak self] _ in self?.suspend("lock")
    }
    distributed.addObserver(forName: .init("com.apple.screenIsUnlocked"), object: nil, queue: .main) {
      [weak self] _ in self?.resume("lock")
    }
  }

  private func suspend(_ reason: String) {
    suspendedBy.insert(reason)
    guard timer != nil else { return }
    NSLog("ClipFlow: capture suspended (\(reason))")
    stop()
  }

  /// Restarts only once every reason has cleared. `isPaused` is untouched, so a
  /// user pause survives a sleep/wake cycle.
  ///
  /// The first tick after resuming sees a `changeCount` that moved while we were
  /// down and captures whatever is on the pasteboard now — the same thing that
  /// happens after any other gap, and the alternative is silently losing a copy
  /// made between an unlock and the next tick.
  private func resume(_ reason: String) {
    suspendedBy.remove(reason)
    guard suspendedBy.isEmpty, timer == nil else { return }
    NSLog("ClipFlow: capture resumed (\(reason))")
    start()
  }

  func start() {
    guard timer == nil else { return }
    let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
      self?.tick()
    }
    // Lets the OS coalesce our wakeups with others instead of demanding a
    // precise 500 ms, which is what keeps idle CPU under the NFR budget.
    timer.tolerance = 0.2
    RunLoop.main.add(timer, forMode: .common)
    self.timer = timer
  }

  func stop() {
    timer?.invalidate()
    timer = nil
  }

  /// Call after writing to the pasteboard ourselves, passing the change count
  /// the write produced. Takes the observed value rather than guessing at
  /// `current + 1`, because how many times a write bumps the counter depends on
  /// how it was performed.
  func ignore(changeCount: Int) {
    ignoredChangeCount = changeCount
  }

  /// FR-7.4 and FR-7.3 both have two front ends — the status menu and the
  /// Settings window — so both go through one setter that announces the change.
  /// Anything drawing this state (the menu bar icon, the Settings checkbox)
  /// listens rather than polls, which is what keeps them from disagreeing after
  /// an armed capture is spent by a copy the user made somewhere else.
  func setPaused(_ paused: Bool) {
    guard paused != isPaused else { return }
    Preferences.isPaused = paused
    NSLog("ClipFlow: capture \(paused ? "paused" : "unpaused") by user")
    announceStateChange()
  }

  func setIgnoresNextCapture(_ ignores: Bool) {
    guard ignores != ignoresNextCapture else { return }
    ignoresNextCapture = ignores
    announceStateChange()
  }

  private func announceStateChange() {
    NotificationCenter.default.post(name: .clipFlowCaptureStateChanged, object: nil)
  }

  private func tick() {
    let current = pasteboard.changeCount
    guard current != lastChangeCount else { return }
    lastChangeCount = current

    guard !isPaused else { return }

    if ignoredChangeCount == current {
      ignoredChangeCount = nil
      return
    }

    // FR-7.3, and it is spent here rather than in `capture()` for two reasons:
    // our own paste writes are filtered out just above, so arming it can never be
    // consumed by the app's own pasteboard traffic; and it suppresses the copy
    // whatever it turns out to contain, including the sizes and types `capture()`
    // would have rejected on its own.
    if ignoresNextCapture {
      NSLog("ClipFlow: ignored one copy on request")
      setIgnoresNextCapture(false)
      return
    }

    Task { @MainActor in
      try? await Task.sleep(for: Self.settleDelay)
      // Another copy landed while we waited; the next tick will handle it.
      guard self.pasteboard.changeCount == current else { return }
      self.capture()
    }
  }

  @MainActor
  private func capture() {
    let types = Set(pasteboard.types ?? [])
    guard types.isDisjoint(with: Self.skipTypes) else { return }

    let app = NSWorkspace.shared.frontmostApplication

    // FR-7.2. Checked against the app that is frontmost at capture time — the
    // same one recorded as `source_bundle_id` — so exclusion means exactly what
    // the list in Settings shows. Before anything is hashed or written: an
    // excluded app's contents must not reach disk even long enough to be swept.
    if let bundleID = app?.bundleIdentifier, Preferences.excludedBundleIDs.contains(bundleID) {
      NSLog("ClipFlow: skipped copy from excluded app \(bundleID)")
      return
    }

    let now = Int64(Date().timeIntervalSince1970 * 1000)

    // FR-1.2's priority order, applied as a fixed sequence rather than by asking
    // the pasteboard what it prefers. Copying from Word or a browser puts PNG,
    // TIFF, RTF and plain text down at once, and the same copy has to classify
    // identically on every run (PRD HP-3).
    //
    // An image present at all settles the kind; this is not a fallback chain.
    // Written as one it inserted a stray text row every time a screenshot was
    // re-copied, because the dedupe hit looked the same as "no image here".
    if let png = pngFromPasteboard() {
      guard let item = imageItem(png: png, app: app, at: now) else { return }
      ItemRepository.save(item)
      // FR-4.1: the row is enqueued by being inserted 'pending'; this only tells
      // an idle worker there is something to do. It returns immediately —
      // nothing about OCR runs on this thread (FR-4.4).
      OCRQueue.shared.wake()
      return
    }

    guard let item = textItem(app: app, at: now) else { return }
    ItemRepository.save(item)
  }

  @MainActor
  private func imageItem(png: Data, app: NSRunningApplication?, at now: Int64) -> Item? {
    guard png.count <= Self.maxImageBytes else { return nil }

    // Before writing anything: a re-copied screenshot is a dedupe hit
    // (DECISIONS D-5b), and discovering that after writing several megabytes to
    // disk would leave a file to sweep every time.
    let hash = Self.hash(png)
    if ItemRepository.bump(contentHash: hash, at: now) { return nil }

    guard let stored = ImageStore.save(png: png) else { return nil }

    return Item(
      kind: .image,
      content: nil,
      // `preview` is NOT NULL and image rows have no text, so it carries the one
      // thing that identifies the image without opening it.
      preview: "Image \(stored.pixelWidth) × \(stored.pixelHeight)",
      imagePath: stored.relativePath,
      sourceBundleID: app?.bundleIdentifier,
      sourceAppName: app?.localizedName,
      copiedAt: now,
      contentHash: hash,
      ocrStatus: .pending
    )
  }

  @MainActor
  private func textItem(app: NSRunningApplication?, at now: Int64) -> Item? {
    guard let content = pasteboard.string(forType: .string),
          !content.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
          content.utf8.count <= Self.maxContentBytes
    else { return nil }

    // FR-1.2 ranks `public.rtf` above plain text, but both are the same kind of
    // item — so RTF is an extra representation on a text row, not a different
    // classification. Read explicitly rather than asking the pasteboard which
    // type it prefers, so a Word copy classifies identically on every run
    // (PRD HP-3).
    var rtf = pasteboard.data(forType: .rtf)
    if let data = rtf, data.count > Self.maxRTFBytes { rtf = nil }

    return Item(
      kind: .text,
      content: content,
      preview: Self.preview(of: content),
      rtfData: rtf,
      sourceBundleID: app?.bundleIdentifier,
      sourceAppName: app?.localizedName,
      copiedAt: now,
      contentHash: Self.hash(content),
      // FR-5.1. Detected here rather than lazily on selection so the list can
      // draw FR-6.4's glyph without touching `content` at all — and so a row is
      // never briefly wrong about whether it has a link. Bounded by
      // `URLDetector.scanLimit`, which is what keeps this off the copy path's
      // critical timing.
      detectedURLs: URLDetector.json(for: content)
    )
  }

  /// PNG is preferred and used as-is; TIFF is transcoded, because FR-2.2 names
  /// PNG as the on-disk format and a TIFF screenshot is several times larger for
  /// the same pixels.
  @MainActor
  private func pngFromPasteboard() -> Data? {
    if let png = pasteboard.data(forType: .png) { return png }
    guard let tiff = pasteboard.data(forType: .tiff) else { return nil }
    return NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:])
  }

  /// Beyond this a preview is only the opening of the item, so two different
  /// items can render as the same row — which is what `ItemSummary.sizeHint`
  /// exists to disambiguate.
  static let previewLimit = 200

  /// Collapses whitespace so multi-line stack traces stay readable in one row.
  static func preview(of content: String) -> String {
    let collapsed = content
      .trimmingCharacters(in: .whitespacesAndNewlines)
      .split(whereSeparator: \.isWhitespace)
      .joined(separator: " ")
    return String(collapsed.prefix(previewLimit))
  }

  static func hash(_ content: String) -> String {
    hash(Data(content.utf8))
  }

  static func hash(_ data: Data) -> String {
    SHA256.hash(data: data)
      .compactMap { String(format: "%02x", $0) }
      .joined()
  }
}
