import AppKit
import CryptoKit
import Foundation

/// There is no clipboard-change notification on macOS. None. Polling
/// `changeCount` is the only approach (PRD HP-1), and it's what every clipboard
/// manager does.
final class PasteboardMonitor {
  static let shared = PasteboardMonitor()

  /// Apps that mark their pasteboard contents as not-for-history.
  /// 1Password, Bitwarden, and Apple Passwords set `ConcealedType`.
  private static let skipTypes: Set<NSPasteboard.PasteboardType> = [
    .init("org.nspasteboard.ConcealedType"),
    .init("org.nspasteboard.TransientType"),
    .init("org.nspasteboard.AutoGeneratedType"),
  ]

  /// A single copy of a 50 MB log file would blow both the 5 MB database budget
  /// and the 60 MB memory budget (DECISIONS S-4).
  private static let maxContentBytes = 1_000_000

  /// Images get their own, more generous cap: they go to disk rather than into
  /// SQLite (FR-2.2), so the 1 MB text limit — which exists to protect the 5 MB
  /// database budget — does not apply. A full-screen PNG on a 6K Retina display
  /// runs 5–15 MB, so anything under that would reject ordinary screenshots.
  /// 32 MB still bounds the transient decode against the memory budget.
  private static let maxImageBytes = 32_000_000

  /// Password managers `declareTypes` and then `setData`. A poll landing between
  /// the two reads the string before `ConcealedType` is declared and stores the
  /// password silently. Waiting for the change count to hold still closes that
  /// window (DECISIONS S-2).
  private static let settleDelay: Duration = .milliseconds(80)

  private let pasteboard = NSPasteboard.general
  private var timer: Timer?
  private var lastChangeCount: Int

  /// Set by our own writes to the pasteboard. Without it, every paste bumps
  /// `changeCount`, gets re-captured, and reshuffles the history
  /// (DECISIONS S-1). Phase 4 will call `ignoreNextChange()` from the paster.
  private var ignoredChangeCount: Int?

  var isPaused = false

  private init() {
    lastChangeCount = pasteboard.changeCount
  }

  func start() {
    guard timer == nil else { return }
    let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
      self?.tick()
    }
    // Lets the OS coalesce our wakeups with others instead of demanding a
    // precise 500 ms, which is what keeps idle CPU under the NFR budget.
    timer.tolerance = 0.2
    RunLoop.main.add(timer, forMode: .common)
    self.timer = timer
  }

  func stop() {
    timer?.invalidate()
    timer = nil
  }

  /// Call after writing to the pasteboard ourselves, passing the change count
  /// the write produced. Takes the observed value rather than guessing at
  /// `current + 1`, because how many times a write bumps the counter depends on
  /// how it was performed.
  func ignore(changeCount: Int) {
    ignoredChangeCount = changeCount
  }

  private func tick() {
    let current = pasteboard.changeCount
    guard current != lastChangeCount else { return }
    lastChangeCount = current

    guard !isPaused else { return }

    if ignoredChangeCount == current {
      ignoredChangeCount = nil
      return
    }

    Task { @MainActor in
      try? await Task.sleep(for: Self.settleDelay)
      // Another copy landed while we waited; the next tick will handle it.
      guard self.pasteboard.changeCount == current else { return }
      self.capture()
    }
  }

  @MainActor
  private func capture() {
    let types = Set(pasteboard.types ?? [])
    guard types.isDisjoint(with: Self.skipTypes) else { return }

    let app = NSWorkspace.shared.frontmostApplication
    let now = Int64(Date().timeIntervalSince1970 * 1000)

    // FR-1.2's priority order, applied as a fixed sequence rather than by asking
    // the pasteboard what it prefers. Copying from Word or a browser puts PNG,
    // TIFF, RTF and plain text down at once, and the same copy has to classify
    // identically on every run (PRD HP-3).
    //
    // An image present at all settles the kind; this is not a fallback chain.
    // Written as one it inserted a stray text row every time a screenshot was
    // re-copied, because the dedupe hit looked the same as "no image here".
    if let png = pngFromPasteboard() {
      guard let item = imageItem(png: png, app: app, at: now) else { return }
      ItemRepository.save(item)
      // FR-4.1: the row is enqueued by being inserted 'pending'; this only tells
      // an idle worker there is something to do. It returns immediately —
      // nothing about OCR runs on this thread (FR-4.4).
      OCRQueue.shared.wake()
      return
    }

    guard let item = textItem(app: app, at: now) else { return }
    ItemRepository.save(item)
  }

  @MainActor
  private func imageItem(png: Data, app: NSRunningApplication?, at now: Int64) -> Item? {
    guard png.count <= Self.maxImageBytes else { return nil }

    // Before writing anything: a re-copied screenshot is a dedupe hit
    // (DECISIONS D-5b), and discovering that after writing several megabytes to
    // disk would leave a file to sweep every time.
    let hash = Self.hash(png)
    if ItemRepository.bump(contentHash: hash, at: now) { return nil }

    guard let stored = ImageStore.save(png: png) else { return nil }

    return Item(
      kind: .image,
      content: nil,
      // `preview` is NOT NULL and image rows have no text, so it carries the one
      // thing that identifies the image without opening it.
      preview: "Image \(stored.pixelWidth) × \(stored.pixelHeight)",
      imagePath: stored.relativePath,
      sourceBundleID: app?.bundleIdentifier,
      sourceAppName: app?.localizedName,
      copiedAt: now,
      contentHash: hash,
      ocrStatus: .pending
    )
  }

  @MainActor
  private func textItem(app: NSRunningApplication?, at now: Int64) -> Item? {
    guard let content = pasteboard.string(forType: .string),
          !content.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
          content.utf8.count <= Self.maxContentBytes
    else { return nil }

    return Item(
      kind: .text,
      content: content,
      preview: Self.preview(of: content),
      sourceBundleID: app?.bundleIdentifier,
      sourceAppName: app?.localizedName,
      copiedAt: now,
      contentHash: Self.hash(content)
    )
  }

  /// PNG is preferred and used as-is; TIFF is transcoded, because FR-2.2 names
  /// PNG as the on-disk format and a TIFF screenshot is several times larger for
  /// the same pixels.
  @MainActor
  private func pngFromPasteboard() -> Data? {
    if let png = pasteboard.data(forType: .png) { return png }
    guard let tiff = pasteboard.data(forType: .tiff) else { return nil }
    return NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:])
  }

  /// Beyond this a preview is only the opening of the item, so two different
  /// items can render as the same row — which is what `ItemSummary.sizeHint`
  /// exists to disambiguate.
  static let previewLimit = 200

  /// Collapses whitespace so multi-line stack traces stay readable in one row.
  static func preview(of content: String) -> String {
    let collapsed = content
      .trimmingCharacters(in: .whitespacesAndNewlines)
      .split(whereSeparator: \.isWhitespace)
      .joined(separator: " ")
    return String(collapsed.prefix(previewLimit))
  }

  static func hash(_ content: String) -> String {
    hash(Data(content.utf8))
  }

  static func hash(_ data: Data) -> String {
    SHA256.hash(data: data)
      .compactMap { String(format: "%02x", $0) }
      .joined()
  }
}
